application: strumbook
version: 2.1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
  
- url: /css
  static_dir: css
  
- url: /files
  static_dir: files
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
  
error_handlers:
  - file: default_error.html
